server:
  port: 9090

encrypt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArKM6oGp/PwpExyOIjqIolJQePh+k6s55zHqY77xXWYbAtBqH986ssLq8Nr75yq5ymlOG6VxnQ0KwGzN9RB46Glazd6K2rJ7DOC/fNGsvobRGlqo2qqV90irEFtwzLZA2ML96yUIANQLVmqM4mRo1gIYVaJyKUq+GfuhooviRfnD1JufsP3PAFXldi7A8rzffYYPSplcd50qpcjYGw1k0Pm4I5Kqh6HseB0OoG5hV/VgMO+NiXwf48iOkpLWAGb43hn/xURhnyacv5/4vK4SjJavSG5byn+R/jW+BHAzR72Z5BWAIbNopdAW4MAYAjbOZ9ri4Np0JIW0sQ7P7gbaFIwIDAQAB
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCsozqgan8/CkTHI4iOoiiUlB4+H6TqznnMepjvvFdZhsC0Gof3zqywurw2vvnKrnKaU4bpXGdDQrAbM31EHjoaVrN3orasnsM4L980ay+htEaWqjaqpX3SKsQW3DMtkDYwv3rJQgA1AtWaoziZGjWAhhVonIpSr4Z+6Gii+JF+cPUm5+w/c8AVeV2LsDyvN99hg9KmVx3nSqlyNgbDWTQ+bgjkqqHoex4HQ6gbmFX9WAw742JfB/jyI6SktYAZvjeGf/FRGGfJpy/n/i8rhKMlq9IblvKf5H+Nb4EcDNHvZnkFYAhs2il0BbgwBgCNs5n2uLg2nQkhbSxDs/uBtoUjAgMBAAECggEBAI07kGfSGD2Leg7sS/hcQxSiREeQfcu2lUAqf9mI3HEaY6Y0Gk4p329JpVaoUBR3OLx2XuWkubn14bqvGejTTbdkfLf//rAjxhO+Xj00/yesIx95KvXaI5//aqJFDP1WgG7LB3mErESyB+vVYiUmouR9TSBjCGpyvHYwTgIdlnG4QRv5nEHhQdJdnFdxXOGgg1VJDjGP1utzhTPHhGXrQiJ7frspNCa1+hArWF2vDWKwr+CQpGCe62mQFeFIRZ8jY60KYFCbuZ+6rxW/17VZgT8saPWJ2mJYK2RQ+AcgYexHsJ0b8DfukEbt+aZr+crYC/9/8WE0Tvyo7hCW4F/T3YkCgYEA23xFU+1pwd4yG5DLMWjP/nSrnrhWbydKMr+K6d4QQE6Gg8kkmVGY/++U8gWnfgGMeglSxdg68SdIqZYMxnKN35+gn2cu75IdKuTLpwI1W+w4wk3IM+n1zhZztT5L4fEUDTzmVmkCEmeouNtwsh2bv1hhp5ZxqDHeUiiek9rQZXcCgYEAyVu+I73mIFQrIrqVpbwKTD6BfFiMCYH4cs4XYVcPZbsinwbUeOIV4wcaO2g1U/xlf3IcKNZLexninkRjlP/4mnq37lwMV+/vXYBg03Q5mkYUlRyBqA2qmLXBhLsmGvfVumL0wRljkyR+awiF0OP8y8kR5eQBm6HgoYlVaTlpeLUCgYBRo6rB6ggxdW2b9UKvUTY0hr8jXZvA4pNlxvtrvA69bLf6IwI7CS/o2vvC/jlr1DWlWvxv3Nsnwh3z/n0n/4ooCN8dC6tYrzesMchSia7BT19ZXsc+ECM/EfjeDJr7Isn7lpByycJciDQo9m63we2hwcUpKfuCvXHdi4BYrMZhRwKBgQCyMsXn/bQ+Yh62omezf+GhLiQL9pUgCOzmNSuN0q1mu6FdGX9J59O00mFNt+CSDimJC2SOY2/zZqoepKl4gLvzgq1qff3SiR3OIsIOAKrFtEWc3NiF8GpMsXWs0K9daH22cMLobV6pJr/WW3mJr2rWsoBrckhWAoG4k8CJ2exUjQKBgQCkCyQK4VatFHn0uAPhV8qI5gx5UNcCHIc6CizfJjN3bxkTlXLYrNJ3ytJrkYhkA4XrLX3Y5UtbT+q5LaYeOxrP2bd+wK58jxcOcMkXS6/zQEOrmBTa1u2IwLMJHyNBwvSxKBkeMSTAa8XllGhfg/mMGDOBCA6AaTWsjQw9ShAKnA==

spring:

  #  DATASOURCE MARIADB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/encrypt_db?createDatabaseIfNotExist=true&autoReconnect=true&UseUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect